route:
  receiver: 'webhook'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://app:8080'
        max_alerts: 3
        send_resolved: true
