version: '3.8'
# logger driver - change this driver to ship all container logs to a different location
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
services:
  app:
    <<: *logging
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8080
  prometheus:
    image: prom/prometheus:v2.45.4
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      # NOTE: The naming must be exact. If you use other name or '.yaml' file
      # extension, it will not work.
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
      - ./out.txt:/var/app/out.txt
  grafana:
    image: grafana/grafana:10.3.5-ubuntu
    ports:
      - 127.0.0.1:3000:3000
  grizzly:
    image: grafana/grizzly:main-f431d43
    volumes:
    - .:/src/
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_TOKEN=admin
    working_dir: /src/dashboards/
    # For the first time, you can run `grr pull resources`
    #ash -c "grr pull resources"
    entrypoint: >
      ash -c "grr apply /src/dashboards --continue-on-error"
  loki:
    image: grafana/loki:2.8.11
    ports:
      - 127.0.0.1:3100:3100
    command: -config.file=/etc/loki/local-config.yaml
  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - "./alertmanager.yml:/config/alertmanager.yml"
    command: --config.file=/config/alertmanager.yml --log.level=debug
