version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.45.4
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      # NOTE: The naming must be exact. If you use other name or '.yaml' file
      # extension, it will not work.
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:10.3.5-ubuntu
    ports:
      - 127.0.0.1:3000:3000
  grizzly:
    image: grafana/grizzly:main-f431d43
    volumes:
    - .:/src/
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_TOKEN=admin
    working_dir: /src/dashboards/
    # For the first time, you can run `grr pull resources`
    #ash -c "grr pull resources"
    entrypoint: >
      ash -c "grr apply /src/dashboards --continue-on-error"
