scrape_configs:
- job_name: myapp
  scrape_interval: 5s
  static_configs:
  - targets:
    - host.docker.internal:8000

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
